### PR TITLE
fix: remove label if no longer present

### LINKED ISSUE #4430: can't remove node label
### Describe the bug

Node label can't be removed by setting `label: undefined`. Setting to an empty string does work but this is not a good workaround because if there is a label background, then this is still visible for an empty string.

### Your Example Website or App

https://stackblitz.com/edit/react-spflig-szup5p?file=index.js

### Steps to Reproduce the Bug or Issue

1. try to remove node label with `graph.updateItem(node, { label: undefined })`
2. the node label is not removed

### Expected behavior

I expect to be able to remove the label by setting it to undefined, or null.

### Screenshots or Videos

_No response_

### Platform

- OS: macOS
- Browser: chrome
- Version: 112

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ensconced**
##### Checklist

- [x] `npm test` passes
- [ ] tests and/or benchmarks are included
- [x] commit message follows commit guidelines

##### Description of change

fixes #4430

### CODE REVIEW

File: packages/core/src/element/shapeBase.ts [hunk 1]
```diff
@@ -251,14 +251,23 @@ export const shapeBase: ShapeOptions = {
...
+    const labelClassName = this.itemType + CLS_LABEL_SUFFIX;
+    const label = group['shapeMap'][labelClassName] || group.find(ele => ele.get('className') === labelClassName);
+    const labelBgClassname = this.itemType + CLS_LABEL_BG_SUFFIX;
+    let labelBg = group['shapeMap'][labelBgClassname] || group.find(ele => ele.get('className') === labelBgClassname);
+
+    if (label && cfg.label === undefined) {
+      group.removeChild(label);
+      delete group['shapeMap'][labelClassName];
+      if (labelBg) {
+        group.removeChild(labelBg);
```
Comment (Yanyan-Wang) [inline packages/core/src/element/shapeBase.ts:265]: remove labelBg from group['shapeMap'] here:

delete group['shapeMap'][labelBgClassname];

**Review by Yanyan-Wang — CHANGES_REQUESTED** [review]

**Comment by Yanyan-Wang** [comment]
Thanks for your Pull Request! Please check out the comments.

File: packages/core/src/element/shapeBase.ts (hunk 1 above)
Comment (ensconced) [reply packages/core/src/element/shapeBase.ts:265]: makes sense, done 🙂
